//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManutencaoQuiminvest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManutencaoEntities : DbContext
    {
        public ManutencaoEntities()
            : base("name=ManutencaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entrada> Entrada { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Saida> Saida { get; set; }
    }
}
