//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManutencaoQuiminvest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int Id { get; set; }
        public string Produtos { get; set; }
        public string Tipo { get; set; }
        public string Fabricante { get; set; }
        public string Forcenecedor { get; set; }
        public string Modelo { get; set; }
        public string Descricao { get; set; }
        public string Telefone { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
    }
}
