//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManutencaoQuiminvest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saida
    {
        public int Id { get; set; }
        public string Produto { get; set; }
        public string Tipo { get; set; }
        public string Descricao { get; set; }
        public string ResponsavelEntrada { get; set; }
        public int QtdSaida { get; set; }
        public string Responsavel { get; set; }
        public string Motivo { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public int QtdEstoque { get; set; }
    }
}
