//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaQuiminvest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtrlNotasFiscais
    {
        public int Id { get; set; }
        public string Fornecedor { get; set; }
        public string Produto { get; set; }
        public string Entrega { get; set; }
        public string Recebido { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public string NumeroNF { get; set; }
    }
}
