//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaQuiminvest.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reatorEntities : DbContext
    {
        public reatorEntities()
            : base("name=reatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<controle> controle { get; set; }
        public virtual DbSet<CtrlNotasFiscais> CtrlNotasFiscais { get; set; }
        public virtual DbSet<EntradaSaida> EntradaSaida { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<OrdemP> OrdemPSet { get; set; }
    }
}
