//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaQuiminvest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemP
    {
        public int Id { get; set; }
        public string ProdutoOP { get; set; }
        public string LoteOP { get; set; }
        public string DataOP { get; set; }
        public string HoraOP { get; set; }
        public string Nome1 { get; set; }
        public string Nome2 { get; set; }
        public string Nome3 { get; set; }
        public string HO1 { get; set; }
        public string HO2 { get; set; }
        public string HO3 { get; set; }
        public string NomeA1 { get; set; }
        public string NomeA2 { get; set; }
        public string NomeA3 { get; set; }
        public string HA1 { get; set; }
        public string HA2 { get; set; }
        public string HA3 { get; set; }
        public string Materia1 { get; set; }
        public string Materia2 { get; set; }
        public string Materia3 { get; set; }
        public string LM1 { get; set; }
        public string LM2 { get; set; }
        public string LM3 { get; set; }
        public string Qtd1 { get; set; }
        public string Qtd2 { get; set; }
        public string Qtd3 { get; set; }
        public string Observacao { get; set; }
    }
}
