//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEDB.LOCADORA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacao
    {
        public int QtdDia { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public Nullable<double> Comissao { get; set; }
        public int CodC { get; set; }
        public int CodV { get; set; }
        public int CodLoc { get; set; }
        public int CodF { get; set; }
    
        public virtual Clientee Clientee { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
