//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK.DESKTOP.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroJogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroJogo()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int CodigoJogo { get; set; }
        public byte[] FotoJ { get; set; }
        public string LocalizacaoJ { get; set; }
        public string RuaJ { get; set; }
        public string Bairroj { get; set; }
        public string Cidadej { get; set; }
        public string Ufj { get; set; }
        public string QtdPessoas { get; set; }
        public string Dataj { get; set; }
        public string AddMembrosj { get; set; }
        public string DescricaoJ { get; set; }
        public string Valorj { get; set; }
        public string AddObjeto { get; set; }
        public string TipoJ { get; set; }
        public string Telefone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
