//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK.DESKTOP.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroUsuario
    {
        public int CodigoUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public string SenhaUsuario { get; set; }
        public string ConfSenha { get; set; }
        public byte[] FotoUsuario { get; set; }
        public string DataNascUsua { get; set; }
    }
}
