//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK.DESKTOP.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroHotel()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int CodigoHotel { get; set; }
        public byte[] FotoHotel { get; set; }
        public string Ruah { get; set; }
        public string Bairroh { get; set; }
        public string Cidadeh { get; set; }
        public string Ufh { get; set; }
        public string DescricaoHotel { get; set; }
        public string NomeCliente { get; set; }
        public string DescricaoCliente { get; set; }
        public string Categoria { get; set; }
        public string Valorh { get; set; }
        public string LocalizacaoH { get; set; }
        public string ReferenciaH { get; set; }
        public string Telefone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
