//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK.DESKTOP.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroCliente
    {
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string TipoEvento { get; set; }
        public string Idade { get; set; }
        public byte[] Foto { get; set; }
        public string Descricao { get; set; }
        public string Sexo { get; set; }
        public string DataNasc { get; set; }
        public string Cnpj { get; set; }
        public int CodigoCliente { get; set; }
        public string EmailCliente { get; set; }
        public string SenhaCliente { get; set; }
        public string ConfCliente { get; set; }
        public string Telefone { get; set; }
    }
}
