//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK.DESKTOP.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public byte[] FotoCons { get; set; }
        public string DescricaoCons { get; set; }
        public int CodigoConsulta { get; set; }
        public string LocalizacaoCons { get; set; }
        public string RuaCons { get; set; }
        public string BairroCons { get; set; }
        public string CidadeCons { get; set; }
        public string UfCons { get; set; }
        public string DataCons { get; set; }
        public string ValorCons { get; set; }
        public byte[] FotoClienteCons { get; set; }
        public string DescricaoClienteCons { get; set; }
        public string TipoEventoCons { get; set; }
        public string DescricaoGeral { get; set; }
        public Nullable<int> Registro { get; set; }
    
        public virtual CadastroFesta CadastroFesta { get; set; }
        public virtual CadastroHotel CadastroHotel { get; set; }
        public virtual CadastroJogo CadastroJogo { get; set; }
    }
}
