//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertCity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaRegistros01
    {
        public int Registros { get; set; }
        public int RegistroID { get; set; }
        public string Rua { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public System.DateTime Data { get; set; }
        public byte[] Imagem { get; set; }
        public string Descricao { get; set; }
    
        public virtual BuracoReg BuracoReg { get; set; }
        public virtual FocosReg FocosReg { get; set; }
        public virtual IntoxicacaoReg IntoxicacaoReg { get; set; }
        public virtual VazamentoReg VazamentoReg { get; set; }
        public virtual ViolenciaReg ViolenciaReg { get; set; }
    }
}
