//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertCity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alextheodoroEntities : DbContext
    {
        public alextheodoroEntities()
            : base("name=alextheodoroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appCadastroUsuario> appCadastroUsuario { get; set; }
        public virtual DbSet<appLogin> appLogin { get; set; }
        public virtual DbSet<BuracoReg> BuracoReg { get; set; }
        public virtual DbSet<ConsultaRegistros01> ConsultaRegistros01 { get; set; }
        public virtual DbSet<FocosReg> FocosReg { get; set; }
        public virtual DbSet<IntoxicacaoReg> IntoxicacaoReg { get; set; }
        public virtual DbSet<VazamentoReg> VazamentoReg { get; set; }
        public virtual DbSet<ViolenciaReg> ViolenciaReg { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
    }
}
