//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertCity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int RegistroEvento { get; set; }
        public string Localizacaof { get; set; }
        public string Ruaf { get; set; }
        public string Bairrof { get; set; }
        public string Cidadef { get; set; }
        public string Uff { get; set; }
        public string Cepf { get; set; }
        public System.DateTime Dataf { get; set; }
        public string DescricaoEvento { get; set; }
        public string Valorf { get; set; }
        public string TipoF { get; set; }
        public string Telefone { get; set; }
    }
}
