//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertCity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VazamentoReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VazamentoReg()
        {
            this.ConsultaRegistros01 = new HashSet<ConsultaRegistros01>();
        }
    
        public int RegistroVazamento { get; set; }
        public byte[] FotoVaz { get; set; }
        public System.DateTime DataVazamento { get; set; }
        public string CidadeVaz { get; set; }
        public string BairroVaz { get; set; }
        public string RuaVaz { get; set; }
        public string DescricaoVaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaRegistros01> ConsultaRegistros01 { get; set; }
    }
}
