//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertCity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViolenciaReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ViolenciaReg()
        {
            this.ConsultaRegistros01 = new HashSet<ConsultaRegistros01>();
        }
    
        public int RegistroViolencia { get; set; }
        public byte[] FotoVio { get; set; }
        public System.DateTime DataViolencia { get; set; }
        public string RuaVio { get; set; }
        public string CidadeVio { get; set; }
        public string BairroVio { get; set; }
        public string DescricaoVio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaRegistros01> ConsultaRegistros01 { get; set; }
    }
}
