//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiminVestReator
{
    using System;
    using System.Collections.Generic;
    
    public partial class controle : DbContext
    {
        public tccEntities()
            : base("name=tccEntities")
        {


        }
  
        public string Etapa { get; set; }
        public string Hora { get; set; }
        public string Data { get; set; }
        public string VolDestilado { get; set; }
        public string Caldeira { get; set; }
        public string Reator { get; set; }
        public string Fluido { get; set; }
        public string PressaoMmHg { get; set; }
        public string AgitacaoRpm { get; set; }
        public string AmperagemA { get; set; }
        public int Id { get; set; }
    }
}
