//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiminVestReator
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaSaida
    {
        public int Id { get; set; }
        public string Funcionario { get; set; }
        public string Veiculo { get; set; }
        public string Placa { get; set; }
        public string HoraEntrada { get; set; }
        public string HoraSaida { get; set; }
        public string KmEntrada { get; set; }
        public string KmSaida { get; set; }
        public string Data { get; set; }
        public string Destino { get; set; }
    }
}
